### ISSUE TITLE
A playbook that documents the different timestamps that are used in MISP

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-playbooks#42]
### The title of the playbook

MISP timestamp detailss

### Purpose of the playbook

A playbook that documents the different timestamps that are used in MISP.
Go through the timestamp for publishing and last changes as well as how these can be used in search queries.
Document what changes a timestamp in a MISP event.

### External resources used by this playbook

None

### Target audience

CTI

**Comment by adulau** [comment]
Very good idea!
