### ISSUE TITLE
[bug] pb_using_timestamps_in_MISP incorrect publish_timestamp filtering

### ISSUE THREAD

**Issue by righel** [MISP/misp-playbooks#54]
In the timestamps playbook: 
https://github.com/MISP/misp-playbooks/blob/main/misp-playbooks/pb_using_timestamps_in_MISP-with_output.ipynb

Section:
**Use REST API to search for published events on an exact date**
json={"returnFormat":"json", "publish_timestamp":"2023-07-07", "published":"1"}

The `publish_timestamp` filter is not working as expected with the YYYY-MM-DD format, it has to be in timestamp format.

**Comment by cudeso** [comment]
Good catch! I'll update the playbook soon.

**Comment by cudeso** [comment]
Fixed by adding a function date_to_unix_timestamp and using it in the REST search. Thank you for reporting.
